[2024-12-23T16:04:49.031+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-12-23T16:04:49.066+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: asdadas3.NLP_POSTS_UNITED scheduled__2024-12-23T15:55:00+00:00 [queued]>
[2024-12-23T16:04:49.075+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: asdadas3.NLP_POSTS_UNITED scheduled__2024-12-23T15:55:00+00:00 [queued]>
[2024-12-23T16:04:49.076+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 6
[2024-12-23T16:04:49.091+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): NLP_POSTS_UNITED> on 2024-12-23 15:55:00+00:00
[2024-12-23T16:04:49.099+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'asdadas3', 'NLP_POSTS_UNITED', 'scheduled__2024-12-23T15:55:00+00:00', '--job-id', '2', '--raw', '--subdir', 'DAGS_FOLDER/raw_data_scheduling.py', '--cfg-path', '/tmp/tmp0y_v8x_b']
[2024-12-23T16:04:49.102+0000] {standard_task_runner.py:91} INFO - Job 2: Subtask NLP_POSTS_UNITED
[2024-12-23T16:04:49.108+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=102) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-12-23T16:04:49.110+0000] {standard_task_runner.py:64} INFO - Started process 111 to run task
[2024-12-23T16:04:49.169+0000] {task_command.py:426} INFO - Running <TaskInstance: asdadas3.NLP_POSTS_UNITED scheduled__2024-12-23T15:55:00+00:00 [running]> on host 99efd92458ef
[2024-12-23T16:04:49.275+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Zhang_Yuan' AIRFLOW_CTX_DAG_ID='asdadas3' AIRFLOW_CTX_TASK_ID='NLP_POSTS_UNITED' AIRFLOW_CTX_EXECUTION_DATE='2024-12-23T15:55:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-12-23T15:55:00+00:00'
[2024-12-23T16:04:49.276+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-12-23T16:06:04.731+0000] {local_task_job_runner.py:313} WARNING - State of this instance has been externally set to None. Terminating instance.
[2024-12-23T16:06:04.732+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-12-23T16:06:04.734+0000] {process_utils.py:132} INFO - Sending 15 to group 111. PIDs of all processes in the group: [111]
[2024-12-23T16:06:04.735+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 111
[2024-12-23T16:06:04.736+0000] {taskinstance.py:2611} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-12-23T16:06:04.736+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-12-23T16:06:04.748+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/raw_data_scheduling.py", line 71, in main
    time.sleep(180)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 2613, in signal_handler
    raise AirflowTaskTerminated("Task received SIGTERM signal")
airflow.exceptions.AirflowTaskTerminated: Task received SIGTERM signal
[2024-12-23T16:06:04.763+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=asdadas3, task_id=NLP_POSTS_UNITED, run_id=scheduled__2024-12-23T15:55:00+00:00, execution_date=20241223T155500, start_date=20241223T160449, end_date=20241223T160604
[2024-12-23T16:06:04.777+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 2 for task NLP_POSTS_UNITED ((psycopg2.errors.ForeignKeyViolation) insert or update on table "task_fail" violates foreign key constraint "task_fail_ti_fkey"
DETAIL:  Key (dag_id, task_id, run_id, map_index)=(asdadas3, NLP_POSTS_UNITED, scheduled__2024-12-23T15:55:00+00:00, -1) is not present in table "task_instance".

[SQL: INSERT INTO task_fail (task_id, dag_id, run_id, map_index, start_date, end_date, duration) VALUES (%(task_id)s, %(dag_id)s, %(run_id)s, %(map_index)s, %(start_date)s, %(end_date)s, %(duration)s) RETURNING task_fail.id]
[parameters: {'task_id': 'NLP_POSTS_UNITED', 'dag_id': 'asdadas3', 'run_id': 'scheduled__2024-12-23T15:55:00+00:00', 'map_index': -1, 'start_date': datetime.datetime(2024, 12, 23, 16, 4, 49, 67061, tzinfo=Timezone('UTC')), 'end_date': datetime.datetime(2024, 12, 23, 16, 6, 4, 763393, tzinfo=Timezone('UTC')), 'duration': 75}]
(Background on this error at: https://sqlalche.me/e/14/gkpj); 111)
[2024-12-23T16:06:04.788+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=111, status='terminated', exitcode=1, started='16:04:48') (111) terminated with exit code 1
