[2024-12-23T16:06:16.306+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-12-23T16:06:16.347+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: asdadas3.NLP_POSTS_UNITED scheduled__2024-12-23T16:00:00+00:00 [queued]>
[2024-12-23T16:06:16.356+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: asdadas3.NLP_POSTS_UNITED scheduled__2024-12-23T16:00:00+00:00 [queued]>
[2024-12-23T16:06:16.357+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 6
[2024-12-23T16:06:16.373+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): NLP_POSTS_UNITED> on 2024-12-23 16:00:00+00:00
[2024-12-23T16:06:16.381+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'asdadas3', 'NLP_POSTS_UNITED', 'scheduled__2024-12-23T16:00:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/raw_data_scheduling.py', '--cfg-path', '/tmp/tmptu4s800l']
[2024-12-23T16:06:16.384+0000] {standard_task_runner.py:91} INFO - Job 3: Subtask NLP_POSTS_UNITED
[2024-12-23T16:06:16.391+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=145) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-12-23T16:06:16.392+0000] {standard_task_runner.py:64} INFO - Started process 154 to run task
[2024-12-23T16:06:16.447+0000] {task_command.py:426} INFO - Running <TaskInstance: asdadas3.NLP_POSTS_UNITED scheduled__2024-12-23T16:00:00+00:00 [running]> on host 99efd92458ef
[2024-12-23T16:06:16.544+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Zhang_Yuan' AIRFLOW_CTX_DAG_ID='asdadas3' AIRFLOW_CTX_TASK_ID='NLP_POSTS_UNITED' AIRFLOW_CTX_EXECUTION_DATE='2024-12-23T16:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-12-23T16:00:00+00:00'
[2024-12-23T16:06:16.545+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-12-24T14:17:08.490+0000] {local_task_job_runner.py:214} ERROR - Heartbeat time limit exceeded!
[2024-12-24T14:17:08.876+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-12-24T14:17:09.016+0000] {process_utils.py:132} INFO - Sending 15 to group 154. PIDs of all processes in the group: [154]
[2024-12-24T14:17:09.032+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 154
[2024-12-24T14:17:09.146+0000] {taskinstance.py:2611} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-12-24T14:17:09.349+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-12-24T14:17:10.354+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/raw_data_scheduling.py", line 71, in main
    time.sleep(180)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 2613, in signal_handler
    raise AirflowTaskTerminated("Task received SIGTERM signal")
airflow.exceptions.AirflowTaskTerminated: Task received SIGTERM signal
[2024-12-24T14:17:10.645+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=asdadas3, task_id=NLP_POSTS_UNITED, run_id=scheduled__2024-12-23T16:00:00+00:00, execution_date=20241223T160000, start_date=20241223T160616, end_date=20241224T141710
[2024-12-24T14:17:11.579+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=154, status='terminated', exitcode=2, started='16:06:16') (154) terminated with exit code 2
